### ISSUE TITLE
Merges

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#12]
@ronawho -- could you make a pull request for your timing branches? Would be nice to consolidate these in.

If you have no objections, I think I will merge the SerialFFTW branch with master. I'll probably tag the original version as well as the tip of this branch.

**Comment by ronawho** [comment]
PR is up: https://github.com/npadmana/DistributedFFT/pull/14

I agree about merging SerialFFTW in master

**Comment by npadmana** [comment]
Done. Also created a README to keep track of tag info.
