### ISSUE TITLE
Why OOM for Class F on 64 nodes?

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#16]
#14 reports an OOM for Class F on 64 nodes for the Chapel version but not the MPI version. Worth tracking down why this happens...

**Comment by ronawho** [comment]
We could end up using a lot of space for task stacks. The current bulk-comm ends up creating a lot of remote tasks as noted in https://github.com/npadmana/DistributedFFT/issues/4. Each task has an 8MB stack so that could add up.

I'll try with the prototype code in https://github.com/npadmana/DistributedFFT/issues/4#issuecomment-522107502 that eliminates the tasks from comm, or we can try lowering task stacks with `CHPL_RT_CALL_STACK_SIZE=1M` or something.

**Comment by ronawho** [comment]
Also worth noting there are 128 GB nodes (and we probably have access to ~115-120 GB per node between hugepage fragmentation and memory used for the OS.)

**Comment by ronawho** [comment]
Even with 2M hugepages to limit fragmentation, `CHPL_RT_CALL_STACK_SIZE=256K` to limit stack sizes, and applying https://github.com/npadmana/DistributedFFT/issues/4#issuecomment-522107502 to limit stack sizes I still see OOMs.

The line that leads to OOM is:
https://github.com/npadmana/DistributedFFT/blob/bf40d241b6471306f9ce646b4d492fee8a96e8d7/src/DistributedFFT.chpl#L390

but it's possible other areas also increasing overall memory pressure.

Size F is `4096 x 4096 x 8192` ft_transposed has 4 arrays over that size. `W`, `V`, and `Wt` are `complex` and `Twiddle` is `real`. That should be:

`( (4096*4096*8192) * (16 + 16 + 16 + 8) ) / 2^30 / 64 `  is 112 GB / locale just for the arrays, and we could easily be using up the rest on task stacks or temps.

**Comment by npadmana** [comment]
Yeah, each plane is 0.5 GB, and I could easily imagine generating a single task per core, so 16 GB. Which takes us to OOM. 

For the transposed case, we could get around this by first storing in the transposed array and then doing the FFT, instead of the using a temporary array. We might get a small perf bump from that as well. For the non-transposed case, we're not using the extra array so we're all good.

**Comment by npadmana** [comment]
Just for my own edification --- how did you determine where the OOM was happening? Just trying to learn some new tricks....

**Comment by ronawho** [comment]
We should just print the responsible line. For example:

https://github.com/npadmana/DistributedFFT/blob/bf40d241b6471306f9ce646b4d492fee8a96e8d7/runs/ronawho-2019-08-15-NPB-FT/cray-xc/graphs/raw-data/chapel.ft_transposed.F.64.out#L1-L5

**Comment by ronawho** [comment]
FYI I was able to run the non-transposed ft version for size F at 64 locales.

**Comment by ronawho** [comment]
> Yeah, each plane is 0.5 GB, and I could easily imagine generating a single task per core, so 18 GB. Which takes us to OOM.

Ah yeah, that'll easily OOM. 

> For the transposed case, we could get around this by first storing in the transposed array and then doing the FFT, instead of using the temporary myplane arrays. We might get a small perf bump from that as well. For the non-transposed case, we're not using the extra array so we're all good.

Interesting, I'd be curious to see that. Will that result in plan creation for each iteration? If so I'm not sure what that will do with contention on the plan creation lock. It should be fine if plan creation is really fast, but if it's a bottleneck I wonder if there's a way to create a plan and just bump the array pointer each time? (noting that I'm not familiar with fftw at all, so that may be a really naive thought)

**Comment by npadmana** [comment]
I'm going to do what we did with the yz transform, reusing the same plans. I'll have to force using UNALIGNED FFTs, which might disable some operations, but not copying the data may well overcome any benefits from vectorization.

**Comment by npadmana** [comment]
Proposed bug fix in https://github.com/npadmana/DistributedFFT/tree/oom-fix

@ronawho -- if/when you get a chance, it would be interesting to (a) see if this fixes the OOM (b) make sure we don't have any perf regressions compared to our previous tests.

**Comment by ronawho** [comment]
Yup size F ran with that branch!

I see 816s for Chapel compared to 974s for the reference for size F at 64 nodes. I'll run some other sizes to check performance

**Comment by ronawho** [comment]
Unfortunately performance looks much worse with that branch:

Size D:
-------

| nodes | master  | oom-fix |
| ----- | ------- | ------- |
|  16   |  20.59s | 49.28s  |
|  32   |  14.07s | 38.01s  |
|  64   |   9.39s | 25.48s  |

**Comment by npadmana** [comment]
Boo. This seems too large an effect to just come from the FFTW_UNALIGNED flags. 

I wonder if it is due to 
https://github.com/npadmana/DistributedFFT/blob/202815db6d066ff271463201bf3f4d78f8d2b8b5/src/DistributedFFT.chpl#L423

Note that while the slices have the same size, the indices are swapped and I wonder if the copy is less efficient here.

**Comment by ronawho** [comment]
@benharsh are Block-to-Block bulk transfers slower than Block-to-DR?

**Comment by npadmana** [comment]
I just tried a minor fix where I grabbed the local copy of `dest` and used that as my destination to copy to (cbeb2db).

This seems to get timings in the ~36s range (for size D on 16 locales), but I'm seeing quite large variations between different runs (as low as 26s and as high as 48s). FYI, I run multiple runs within the same interactive job. And I'm using 16M hugepages, if that matters.

**Comment by npadmana** [comment]
This does bring up an interesting question. While improving the general `BlockDist` communications is clearly a win, it's worth noting that the majority of our communication patterns are much more structured. There are two calls

```chpl
blockArr = gatherPlane(iPlane, dest);
// dest = blockArr[..,iPlane,..] 
//   and we know that (a) dest is completely local, and 
// (b) src is only distributed in the first dimension

blockArr.scatterPlane(iPlane,src)
// blockArr[..,iPlane,..] = src
```
which should have less overhead than anything more general. I might imagine writing `gatherPlane` as 
```chpl
coforall loc in Locales { // 
   xRange =  blockArr.localSubdomain(loc).dim(1);
   dest[{xRange, j, zRange}] = blockArr.localSlice({xRange,j,zRange});
}
```

I've written `gather/scatterSlice` as methods on `BlockArr` with the hope that these can plug into the internals of the distribution more easily. 

Is this a worthwhile direction?

**Comment by ronawho** [comment]
Ideally I think we want to optimize our bulk comm so all users benefit, but if you need to workaround that until we can resolve it I think that's reasonable (it also gives us target performance to shoot for)

For `gatherPlane` I think it'd be interesting to compare that version to a serialVersion (where you offset the locale iteration order so you don't end up hitting locales in lockstep -- similiar to https://github.com/npadmana/DistributedFFT/issues/4#issuecomment-522107502)

**Comment by npadmana** [comment]
Yes, I agree that general optimizations are largely the way to go. But I’m
guessing (as in this case) that there will always be cases that the
communication pattern is much simpler and can be optimized somewhat.

Does `chpl__bulkTransferArray` result in a single transfer?

**Comment by ronawho** [comment]
I think there will be some metadata communicated, but for the actual data itself it should be a single comm event.

**Comment by npadmana** [comment]
If you get a chance, here is a test case implementing `gatherPlane` (maybe should be called `scatterPlane`?). Unfortunately, it doesn't appear to actually copy anything over (although simple print statements make it seem like it should do the right thing. My guess is that the problem is with my interpretation of `bulkTransferArray`, but I don't know enough on the internals to track this down.

```chpl
// chpl -schpl_serializeSlices -suseBulkTransfer testGather.chpl
use BlockDist;
use CommDiagnostics;

config const Ng=4;
const Dom = newSlabDom({0.. #Ng, 0.. #Ng, 0.. #Ng});
var A,B : [Dom] complex;

forall (i,j,k) in Dom {
  A[i,j,k] = i*Ng**2 + j*Ng + k;
}

writeln("Comm counts: Gather-Plane");
resetCommDiagnostics();
startCommDiagnostics();
coforall loc in Locales {
  on loc {
    const yChunk = B.localSubdomain().dim(1);

    ref barr = B.localSlice(B.localSubdomain());
    forall j in yChunk {
      A.gatherPlane(j, barr);
    }
  }
}
stopCommDiagnostics();
writeln(getCommDiagnostics());

writeln(A);
writeln(B);

proc newSlabDom(dom: domain) where isRectangularDom(dom) {
  if dom.rank !=3 then compilerError("The domain must be 3D");
  const targetLocales = reshape(Locales, {0.. #numLocales, 0..0, 0..0});
  return dom dmapped Block(boundingBox=dom, targetLocales=targetLocales);
}

proc BlockArr.gatherPlane(iPlane, Dest) {
  // Let me assume that every locale has some data
  const Src = if _privatization then chpl_getPrivatizedCopy(this.type, pid) else this;
  for iloc in 0.. #numLocales {
    const jloc = (here.id + iloc)%numLocales;
    const SrcBlock = Src.dom.locDoms[jloc,0,0].myBlock;
    const xRange = SrcBlock.dim(1);
    const zRange = SrcBlock.dim(3);
    const inters = {xRange,iPlane..iPlane,zRange};
    const destChunk = {iPlane..iPlane,xRange, zRange};
    const elemActual = Src.locArr[jloc,0,0].myElems._value;
    writeln(destChunk," ",inters);
    chpl__bulkTransferArray(Dest, destChunk, elemActual, inters);
  }
}



```

**Comment by ronawho** [comment]
I probably won't get a chance to look this week, but ping me if you haven't heard back from me next week.

**Comment by npadmana** [comment]
Sorry, missed looking at this. The array here is not contiguous, so I think this is exactly what we'd expect... and I don't think there is much more room to do better here.

Given that the `pencilFFT` branch should fix this OOM as well and is certainly performing better for the smaller cases, I think we can close this issue. Let me know if you disagree.

**Comment by ronawho** [comment]
Ah I see. Is it also non-contiguous for the reference version, or are they using a different layout?

**Comment by npadmana** [comment]
Closing this. We now have a number of different strategies that avoid this OOM, with our default option likely being the one on the `elegant` branch.
