### ISSUE TITLE
Locally transpose, then copy?

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#18]
@ronawho -- in the `FFT_X_transposed` code, I replaced

```chpl
              myplane = arr[{xRange,j..j,zRange}];
```
with 
```chpl
              for iloc1 in 0.. #numLocales {
                on Locales[(iloc1+here.id)%numLocales] {
                  const j1 = j;
                  const myLocDom = arr.localSubdomain();
                  const tmpDom = {myLocDom.dim(1), 0..0,myLocDom.dim(3)};
                  var tmpArr : [tmpDom] T;
                  forall (i,jignore,k) in tmpDom do tmpArr[i,0,k] = arr.localAccess[i,j1,k];
                  myplane[tmpDom] = tmpArr;
                }
              }
```
in the hope that that the strided communication is replaced by a contiguous get and that it would speed things up. Unfortunately, no such luck. Any ideas on why this doesn't work?

**Comment by ronawho** [comment]
Weird, I thought I commented on this yesterday -- which part isn't working? Incorrect results, non-contiguous get, bad performance?

**Comment by npadmana** [comment]
This was an exploratory idea that I never really came back to. The goal was to try to turn the strided GETs into a single GET by first locally transposing the data (which would make it contiguous). I never got better performance from this, and it got superseded by the strategy on the `elegant` branch, so I'm closing this.
