### ISSUE TITLE
Elegance vs Performance

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#27]
(this issue was prompted by these comments from @ronawho)

I'm really happy with the performance results, but I worry that it loses a lot of the elegance perspective, especially in the code sample. If I were an outsider I think I'd see that code and go "that's pretty ugly, I guess elegant Chapel doesn't perform well" and then I'd see the performance graphs and wonder how Chapel is beating MPI and assume it's just a very unoptimized MPI version.

Despite me being all about performance, the original "pretty good performance, but very elegant" story resonated better with me than "awesome performance, but rather ugly". In a longer paper, I think that could make for a compelling demonstration of Chapel's multi-resolution design letting you drop down to lower-levels when you need it, but I think it'd be tough to fit that into a short abstract. (although even for a lower-level version ideally, we'd have a user-facing wrapper over the comm primitive.)

**Comment by npadmana** [comment]
We currently have three possible code-paths -

**master (bf40d241b6471306f9ce646)**

This does each of the local `YZ` planes by calling into 2D FFTW routine. It then fetches each `XZ` plane and then transforms in the `X` direction. In many ways, this is rather simple, since it is a rather thin wrapper around FFTW, and performs very well at low node counts.

It has some serious disadvantages:

1. It can use quite a lot of memory (since every thread ends up storing a local plane). This results in eg. an OOM for F (#16). Note that this version does not address #26 (and it's a little tricky to do so here).
2. Even worse, the parallelism is limited by the number of planes, so it quickly saturates compared with the reference.

**elegance**

To address (2) above, one may switch to a 1D version of the code. An elegant Chapel version of the code might look like 
```chpl
coforall loc in Locales {
  on loc {
    // Get dimensions, set up FFTW plans

    // Use this as a temporary work array to
    // avoid rewriting the src array
    var myplane : [{yRange, zRange}] T;

    for ix in xRange {
      // Copy data over. This is a completely
      // local operation, so use localAccess.
      // Or a series of memcpys for performance.
      myplane = src[ix,..,..];

      // z-transform
      forall iz in zRange {
        FFT1D(myplane[y0,iz]);
      }

      // y-transform
      forall iy in yRange {
        FFT1D(myplane[iy,z0]);
        // This is the transpose step
        dest[iy,ix,..] = myplane[iy,..];
      }
    }

    // Wait until all communication is complete
    YZBarrier.barrier();

    // x-transform
    forall (iy,iz) in {destYRange, zRange} {
      FFT1D(dest[iy,x0,iz]);
    }
    
    // All done, FFT is now complete
  }
}
```

Some thoughts --

0. I actually think this still looks quite elegant.
1. Note that I've fused the YZ and X transforms into a single function. I had split them off thinking I could do some other things more elegantly, but I don't think I actually win much here.
2. This version of the code will suffer in a few places -- (a) the communication here is very high level, but I suspect will not perform as well (b) the FFTs are not blocked, and (c) there is an explicit copy to a work array (`myplane`) to avoid overwriting the `src` array. 

But otherwise, it is very similar to our optimized version, and I suspect it will scale rather well.

That being said, I think it's worth keeping this version around as an elegance baseline. And it also gives the Chapel team something to optimize around. Maybe a switch `--elegant`?

**performance**

I actually think it's a small set of steps to go from this elegant version to a more performant version. 

- I would wrap the copy statements to do the copies more efficiently (dropping down to `memcpys`/`chpl_comm_puts`).
- We could write a simple `batched` iterator that simplifies the FFTW batching step.

**Comment by ronawho** [comment]
I think the two things that jumped out at me were the use of the comm primitive and the c_ptrTo calls. In the updated version it was something like:


```chpl
coforall loc in Locales {
  on loc {
    forall (ix, iz) in {xRange, zRange} {
      var elt = c_ptrTo(arr.localAccess[ix, y0, iz]);
      plan_y.execute(elt, elt);
    }

    forall (ix, iy) in {xRange, yRange} {
      var elt = c_ptrTo(arr.localAccess[ix, iy1, z0]);
      plan_z.execute(elt, elt);
      ref srcRef = arr.localAccess[ix, iy, z0];
      ref dstRef = dest[iy,ix,z0]; // Get reference to remote data
      __primitive("chpl_comm_put", srcRef, dstRef.locale.id, dstRef, myLineSize);
    }
  }
}
```

If we could get rid of the c_ptrTo (or hide it in a lower-level layer that does the C interop) and replace the comm primitive with either `dest[iy,ix,..] = arr[ix,iy,..]` (where the Chapel team would need to optimize this) or with some sort of low-level `copy` wrapper (where the Chapel team would need to add this)  I'd be happy with the elegance.

My main concern was that to others those cptr/primitives look quite hacky/non-elegant

**Comment by npadmana** [comment]
@ronawho -- going into office hours, but I did get a somewhat more elegant version (see branch `elegance`). I think I can elide the c_ptrTo stuff. Will get back to this in an hour.

**Comment by npadmana** [comment]
@ronawho -- check out 6644741414af274d259d on branch `elegance`. There is a new switch -- `useElegant` which defaults to `false`. If you set it to true, it uses an elegant version of FFTs (without dropping down to low-level primitives), which isn't very performant. If false, it uses every trick we learned in our optimizations. On the few tests I've done on swan, it's getting very similar (and maybe somewhat better) times than what I was seeing yesterday.

The nice part of the performant version is that I've abstracted away some of the low-level stuff, so it looks similar in many regards to the elegant version.

Oh, and it fixes #26.

**Comment by npadmana** [comment]
Ideally, it would be great to have timings for both `-useElegant=true` and `-useElegant=false`, but that could be in the talk (not in the abstract). Any chance you'll be able to run another suite of timing tests?

**Comment by ronawho** [comment]
I'll see if I can run, but machine is pretty busy ATM. At a quick glance, the default barrier isn't very scalable, you'll probably get better performance with the [AllLocalesBarrier](https://chapel-lang.org/docs/modules/packages/AllLocalesBarriers.html) -- Add a `use AllLocalesBarriers;` and replace the `YZBarrier.barrier();` with `allLocalesBarrier.barrier()`

**Comment by npadmana** [comment]
`AllLocalesBarriers` it is. f4a90dde71d14a6078fe5

Just to pique your interest,  on 32 nodes on Swan --

| Size | Time |
|---|---|
| D | 11.7 | 
| E | 96.3 |

**Comment by ronawho** [comment]
For `useElegance=false` performance is consistency better than FFT-2-comm-yz. Running the `useElegance=true`. So far I only have up to 256 nodes and I would guess I'll lose access before being able to do 512 nodes

**Comment by npadmana** [comment]
Yes, the elegant version is significantly slower, in part because the fine
grained blockdist communication isn’t great. I noticed a pretty big jump up
when I went to using remotePut.

**Comment by ronawho** [comment]
Sorry, I meant I only have 256 nodes for elegance=false, and I was just starting on elegant=true

**Comment by ronawho** [comment]
Results so far (no 512 results, no size F for elegant-true -- I lose access in a few minutes, and probably won't make it through the queue for 512 nodes)

Size D:
=======

| nodes | ref MPI | FFT-2-comm-yz | elegant=false | elegant=true |
| ----- | ------- | ------------- | ------------- | ------------ |
|   1   | 262.2s  | 160.8s        | 146.3s        | 199.1s       |
|   2   | 156.5s  |  94.7s        |  90.4s        | 181.7s       |
|   4   |  93.8s  |  61.7s        |  57.4s        | 101.8s       |
|   8   |  51.0s  |  37.4s        |  33.7s        |  56.9s       |
|  16   |  25.4s  |  21.3s        |  17.4s        |  31.5s       |
|  32   |  14.1s  |  11.6s        |  10.7s        |  17.4s       |
|  64   |  10.4s  |   6.6s        |   5.9s        |  11.8s       |
| 128   |   5.2s  |   3.9s        |   3.3s        |   8.7s       |
| 256   |   2.8s  |   2.3s        |   2.0s        |   6.3s       |
| 512   |   1.6s  |   1.5s        |


Size E:
=======

| nodes | ref MPI | FFT-2-comm-yz | elegant=false | elegant=true |
| ----- | ------- | ------------- | ------------- | ------------ |
|   8   | 510.7s  | 366.4s        | 316.3s        | 674.4s       |
|  16   | 240.1s  | 201.6s        | 162.8s        | 360.2s       |
|  32   | 115.8s  | 105.9s        |  87.3s        | 192.3s       |
|  64   |  59.0s  |  59.4s        |  52.8s        | 147.0s       |
| 128   |  51.8s  |  31.0s        |  28.7s        | 121.1s       |
| 256   |  25.7s  |  18.1s        |  16.1s        |  82.1s       |
| 512   |  12.6s  |  10.0s        |


Size F:
=======

| nodes | ref MPI | FFT-2-comm-yz | elegant=false |
| ----- | ------- | ------------- | ------------- |
|  64   | 974.0s  | 484.0s        | 401.2s        |
| 128   | 457.0s  | 251.4s        | 242.0s        |
| 256   | 266.7s  | 149.5s        | 133.3s        |
| 512   | 133.7s  |  78.2s        |

**Comment by npadmana** [comment]
I think this is a win. :-) It looks like we’ve basically caught up with
master at low node counts. And even the non elegant code isn’t too ugly.

**Comment by ronawho** [comment]
Updated with full numbers. I agree -- looks great! I think perf is caught up with master at low node counts and on par or ahead of FFT-2-comm-yz at higher node counts.


![npb-ft-D-perf](https://user-images.githubusercontent.com/1588337/66014125-a91fad00-e49b-11e9-87e6-2a1077897944.png)
![npb-ft-E-perf](https://user-images.githubusercontent.com/1588337/66014129-ab820700-e49b-11e9-93cc-08651c459b93.png)
![npb-ft-F-perf](https://user-images.githubusercontent.com/1588337/66014133-ade46100-e49b-11e9-9c44-7dea6974ea5c.png)

**Comment by ronawho** [comment]
I have a branch I was playing with to do a little more cleanup -- https://github.com/npadmana/DistributedFFT/compare/elegance...ronawho:elegance-elliot?diff=split

Some of the changes are almost certainly style preferences, but some might be worth bringing to your branch. I think the changes are:
 - Use a hacky pragma to avoid having to pass fftplans by ref everywhere
 - Uppercase Src/Dst arrays (style preference)
 - dest -> dst (nit style preference, I just do this so src/dst have same number of characters)
 - move coforall+on to a single line (maybe, style preference, but I like it for 1 less level of indentation)
 - cleanup x, y, z src/dst component gathering 
 - use parallel slices instead of parallel localAcces
 - play_x -> xPlan (style -- to be camelCase and match things like xdim)
 - add an offset wrapper iterator
 - replace things like `y0` with `ySrc.first` (style preference)

(Swapping the 2 lines with `// Ideal` with `// Better perf`, this is reasonably close to elegance=false performance, at least for 64 node size D

**Comment by npadmana** [comment]
These look great to me! Some comments inline below....

>  - Use a hacky pragma to avoid having to pass fftplans by ref 
>  everywhere

Great.... the with refs were a little tedious.

>  - Uppercase Src/Dst arrays (style preference)
>  - dest -> dst (nit style preference, I just do this so src/dst 
>  have same number of characters)
>  - play_x -> xPlan (style -- to be camelCase and match things 
>  like xdim)
>  - move coforall+on to a single line (maybe, style preference, 
>  but I like it for 1 less level of indentation)

I agree with all of these.

>  - cleanup x, y, z src/dst component gathering 

I keep forgetting I can do this, and I don't think I ever 
internalized the _ placeholder.

>  - use parallel slices instead of parallel localAcces

Agreed that it should be used for the more elegant case....

>  - add an offset wrapper iterator

Nice. 

>  - replace things like `y0` with `ySrc.first` (style preference)

I go back and forth on these. I sometimes worry that there is some 
hidden work in calculating first (and even worse, that it might 
involve communication),
so I tend to pull things out. Mildly defensive/paranoid 
programming on my part.


>
> (Swapping the 2 lines with `// Ideal` with `// Better perf`, 
> this is reasonably close to elegance=false performance, at least 
> for 64 node size D

Yes, that was largely consistent with what I saw as well. I'll 
update the abstract to reflect that.

Should we make the Performant version follow the same? Certainly 
on style....

I'm happy to merge this into elegance!

**Comment by ronawho** [comment]
> Should we make the Performant version follow the same? Certainly
on style....

Yeah, I was starting to look at that -- trying to understand the batchedRange and numTransforms vs numTransforms+1 code ATM

**Comment by npadmana** [comment]
Ok, let me know if you have questions.

**Comment by ronawho** [comment]
For the  non-memcpy changes in https://github.com/npadmana/DistributedFFT/commit/fa6d3c2568f2b62523e60b18e602f5a03abab01e can you check my understanding: 

I think it's basically trying to have each task call into FFTW once and to achieve that it's increasing the number of transforms. However, since the arrays space won't always evenly divide across tasks we have to have 2 plans for x/y so that some tasks can do 1 extra transform.

If that's right, I hoping we can make a `BatchedFftwPlan` or something that takes care of creating both plans, and has procs/iterators to handle the switching of when to use what. Something that at the callsite might look like:


```chpl
// Set up FFTW plans (returns `BatchedFftwPlan`)
var plan_y = setupPlanColumns(T, ftType, {ySrc, zSrc}, numTasks, signOrKind, FFTW_MEASURE);

forall (my_plan_y, myZRange) in plan_y.batch(zSrc) {
  my_plan_y.execute(myplan[0, ySrc.first, myZRange.first]);
}
```

(not sure about some of the type/method names, or exactly what the internals will look yet though)

**Comment by ronawho** [comment]
If you get a chance, would you mind taking a pass through DistributedFFT.chpl on the elegance branch to see if there's functions that can be removed? Semi-related question -- do the warmup routines need to be changed to call the combined xyz fft routine or are they good as-is?

**Comment by npadmana** [comment]
working on this now.... stay tuned.

**Comment by ronawho** [comment]
Performance is identical for `useElegant=false` for size D/E/F between f4a90dd (original elegance) and f2c5b42 (current elegance HEAD we're looking to merge) i.e. there have been no regressions from the cleanups we've done.

**Comment by npadmana** [comment]
Success! Closing......
