### ISSUE TITLE
Add NPB-FT to chapel nightly perf test

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#42]
@ronawho -- this is yours, if you think it would be useful!

**Comment by ronawho** [comment]
For CLA reasons, we might need you to contribute the benchmark and DistributedFFT.chpl, but I'm happy to set up the rest.

It probably won't happen this week or next week, but let me chat with the perf team and see what makes the most sense here. I'm wondering if we should take a snapshot, or if we should clone this repo as part of testing, or something else.

**Comment by ronawho** [comment]
@npadmana would you mind opening a PR to contribute `ft_transposed.chpl` and `DistributedFFT.chpl`? I was originally thinking we might just want to clone your repo, but we'd have to add a lot of `.notest` and other files to appease our testing system.

I think test/npb/ft/npadmana is probably the right place for them to go. If you're ok adding basic correctness testing, I'm happy to add the performance testing infrastructure.

**Comment by npadmana** [comment]
Will do.....

**Comment by npadmana** [comment]
https://github.com/chapel-lang/chapel/pull/14490

**Comment by ronawho** [comment]
https://github.com/chapel-lang/chapel/pull/14540

**Comment by ronawho** [comment]
This can be closed. Results are available at:
 - [16 node XC](https://chapel-lang.org/perf/16-node-xc/?startdate=2019/11/27&enddate=today&graphs=npbftperfmflopsssized) -- Aries network, 28-core Broadwell chips with 128 GB RAM
 - [16 node CS](https://chapel-lang.org/perf/16-node-cs/?startdate=2019/11/29&enddate=today&configs=gnibvlarge,gnibvfast&graphs=npbftperfmflopsssized) -- FDR InfiniBand network, 36 core Broadwell chips with 128 GB RAM
