### ISSUE TITLE
Write a transposed version of the FFT routine

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#5]
A transposed version of the FFT routine could halve the communication costs. We'll restrict to out-of-place transforms.

- [x] Implement a transposed version of the code.
- [x] Implement the benchmark with the transposed version of the code.

**Comment by npadmana** [comment]
Timings here are for NPB Class D on 8 locales

| Type | Time (s) |
|---|----|
| Untransposed | 68 |
| Transposed | 36 |

@ronawho -- FYI.

**Comment by ronawho** [comment]
Awesome!
