### ISSUE TITLE
Write an FFTW MPI version of the NPB benchmark in C

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#6]
For simplicity, focus on the `S` and `D` cases  (`S` for debugging only).

- [ ] Use in-place/non-transposed routines
- [ ] Use in-place/transposed routines
- [ ] Use out-of-place/transposed routines

**Comment by npadmana** [comment]
I think I'm going to close this as "won't fix", especially with #33 in. I don't think we need many more comparisons.....

@ronawho -- any objections?

**Comment by ronawho** [comment]
Agreed
