### ISSUE TITLE
Port fixes from https://github.com/chapel-lang/chapel/pull/21887

### ISSUE THREAD

**Issue by npadmana** [npadmana/DistributedFFT#77]
The PR in https://github.com/chapel-lang/chapel/pull/21887 defined an `init=` and a `pragma` to prevent double deleting FFTW plans. Port these over to this repository.

**Comment by npadmana** [comment]
Hi @ronawho / @bradcray --

When either of you have a chance, could you review the two commits here --
8e96ac4257c013c150be7c6353b5d29357405abc
34a03e83f5079d18f0ecce91e02bcabb304af415

Small upgrades to address the latest changes in Chapel.

**Comment by bradcray** [comment]
1.30 was just released today, so your timing is excellent!

I gave it a quick look and things looked OK to me.  I didn't try compiling and running but expect/hope that you did?  :)

**Comment by npadmana** [comment]
Yes, I did, and even updated the CI to 1.28. I'll go ahead and update to 1.30.

**Comment by ronawho** [comment]
Hi Nikhil!

Looks good to me. For other types we have used `isOwned`, but `isCopy` is just as intuitive.

Let me know when you're done making changes and I'll pull in your latest version to our copy

**Comment by npadmana** [comment]
The latest version in the repository now works with 1.30, so all ready for you. Thanks!
